### ISSUE TITLE
Need Events on end

### ISSUE THREAD

**Issue by LumiProj** [Seesi/JitsiMeet.Xamarin.IOS#8]
Hi,

I am able to use Jitsi in Xamarin Forms only for iOS. Everything is pretty simple to use. Now in my app what I want when user end the call so I wanted to catch that event to perform some other task.
Is there any out there which help me accomplish this task.

Thanks

**Comment by Seesi** [comment]
Hello @LumiProj , please implement "JitsiMeetViewDelegate" interface. 
I believe this will be the method you will need.
`void ConferenceTerminated (NSDictionary data);`

**Comment by Seesi** [comment]
Hello @LumiProj , I just updated the Xamarin Forms sample project to provide you with the changes you will need.
You can override other methods like ConferenceWillJoin etc for granular control.

**Comment by LumiProj** [comment]
Hi,

I have tested and achieved what I was looking for thanks ad highly appreacited.
